### ISSUE TITLE
用 conda 運行時，中文字在 Linux 上無法正常顯示

### ISSUE THREAD

**Issue by GWFrank** [alwaysmle/NTUcourse#1]
### 預期行為

中文能和 README 裡面的 DEMO 一樣正常顯示

### 實際行為

中文字會顯示為方塊，像是字體缺字 (下圖為實際情況)
![](https://i.imgur.com/P8rffx9.png)

### 運行步驟

```
conda create --name NTUcourse python=3.7
conda activate NTUcourse
pip install -r requirements.txt
python my_class.py
``` 

### 運行環境

- OS: Manjaro Linux x86_64
- Kernel: 5.10.52-1-MANJARO
- DE: Plasma 5.22.3
- Conda version: 4.9.2

**Comment by htyangs** [comment]
Hi GWFrank,
感謝你提出這個問題，因為我目前手邊並沒有linux虛擬機無法做測試，查詢網路關於中文字顯示的問題後，
已針對字體部分做修改，請重新下載新的.exe試試看。
若還是不行的話再跟我說，若成功運行的話也沒麻煩告知一聲，感謝。

**Comment by GWFrank** [comment]
用 conda 建的環境來跑的時候會 ~~因為抓不到 `newspaper` 字體而有同樣的錯誤~~ fallback 使用沒有補中文字的字體
但直接用 linux 裡的 python 環境來跑能夠 ~~正確抓到 `newspaper` 字體並顯示~~ fallback 回去使用系統字體 (發現我其實沒有裝 `newspaper` )
[關於 conda 抓不到字體的stackoverflow](https://stackoverflow.com/questions/47769187/make-anacondas-tkinter-aware-of-system-fonts-or-install-new-fonts-for-anaconda)

**Comment by htyangs** [comment]
原來如此，所以意思是只要用系統的python，就可以直接使用預設中文？如果要用conda的，就必須考慮到他有安裝的字型？

**Comment by GWFrank** [comment]
source: [前一個留言裡最後的那個連結](https://stackoverflow.com/questions/47769187/make-anacondas-tkinter-aware-of-system-fonts-or-install-new-fonts-for-anaconda)
應該是說 conda 給 tkinter 用的 library `libtk6.0.so` 在建的時候沒有使用 Freetype library，但有中文的字形是由 Freetype library 管理的，所以抓不到。但 OS 裝的 `libtk6.0so` 有使用 Freetype library，所以能使用有中文的字形。
[缺字形的 Github issue](https://github.com/ContinuumIO/anaconda-issues/issues/6833)
現在的解決方法可能是
1. 用系統的 python & Tk
2. 用加了 Freetype 的 fork ，[這個PR](https://github.com/conda-forge/tk-feedstock/pull/40)好像可以但沒有測試

**Comment by GWFrank** [comment]
因為這個是 conda 的問題，所以我就先關 issue 了。可以考慮在 README 那邊更新一下 Linux 的安裝方法。
